# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2001-2025, Python Software Foundation
# This file is distributed under the same license as the Python package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Python 3.11\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-07-25 16:48+0000\n"
"PO-Revision-Date: 2025-07-18 20:04+0000\n"
"Language-Team: Chinese (China) (https://app.transifex.com/python-doc/teams/5390/zh_CN/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: zh_CN\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: ../../c-api/exceptions.rst:8
msgid "Exception Handling"
msgstr ""

#: ../../c-api/exceptions.rst:10
msgid ""
"The functions described in this chapter will let you handle and raise Python"
" exceptions.  It is important to understand some of the basics of Python "
"exception handling.  It works somewhat like the POSIX :c:data:`errno` "
"variable: there is a global indicator (per thread) of the last error that "
"occurred.  Most C API functions don't clear this on success, but will set it"
" to indicate the cause of the error on failure.  Most C API functions also "
"return an error indicator, usually ``NULL`` if they are supposed to return a"
" pointer, or ``-1`` if they return an integer (exception: the ``PyArg_*`` "
"functions return ``1`` for success and ``0`` for failure)."
msgstr ""

#: ../../c-api/exceptions.rst:20
msgid ""
"Concretely, the error indicator consists of three object pointers: the "
"exception's type, the exception's value, and the traceback object.  Any of "
"those pointers can be ``NULL`` if non-set (although some combinations are "
"forbidden, for example you can't have a non-``NULL`` traceback if the "
"exception type is ``NULL``)."
msgstr ""

#: ../../c-api/exceptions.rst:26
msgid ""
"When a function must fail because some function it called failed, it "
"generally doesn't set the error indicator; the function it called already "
"set it.  It is responsible for either handling the error and clearing the "
"exception or returning after cleaning up any resources it holds (such as "
"object references or memory allocations); it should *not* continue normally "
"if it is not prepared to handle the error.  If returning due to an error, it"
" is important to indicate to the caller that an error has been set.  If the "
"error is not handled or carefully propagated, additional calls into the "
"Python/C API may not behave as intended and may fail in mysterious ways."
msgstr ""

#: ../../c-api/exceptions.rst:37
msgid ""
"The error indicator is **not** the result of :func:`sys.exc_info()`. The "
"former corresponds to an exception that is not yet caught (and is therefore "
"still propagating), while the latter returns an exception after it is caught"
" (and has therefore stopped propagating)."
msgstr ""

#: ../../c-api/exceptions.rst:44
msgid "Printing and clearing"
msgstr ""

#: ../../c-api/exceptions.rst:49
msgid ""
"Clear the error indicator.  If the error indicator is not set, there is no "
"effect."
msgstr ""

#: ../../c-api/exceptions.rst:55
msgid ""
"Print a standard traceback to ``sys.stderr`` and clear the error indicator. "
"**Unless** the error is a ``SystemExit``, in that case no traceback is "
"printed and the Python process will exit with the error code specified by "
"the ``SystemExit`` instance."
msgstr ""

#: ../../c-api/exceptions.rst:60
msgid ""
"Call this function **only** when the error indicator is set.  Otherwise it "
"will cause a fatal error!"
msgstr ""

#: ../../c-api/exceptions.rst:63
msgid ""
"If *set_sys_last_vars* is nonzero, the variables :data:`sys.last_type`, "
":data:`sys.last_value` and :data:`sys.last_traceback` will be set to the "
"type, value and traceback of the printed exception, respectively."
msgstr ""

#: ../../c-api/exceptions.rst:70
msgid "Alias for ``PyErr_PrintEx(1)``."
msgstr ""

#: ../../c-api/exceptions.rst:75
msgid ""
"Call :func:`sys.unraisablehook` using the current exception and *obj* "
"argument."
msgstr ""

#: ../../c-api/exceptions.rst:78
msgid ""
"This utility function prints a warning message to ``sys.stderr`` when an "
"exception has been set but it is impossible for the interpreter to actually "
"raise the exception.  It is used, for example, when an exception occurs in "
"an :meth:`~object.__del__` method."
msgstr ""

#: ../../c-api/exceptions.rst:83
msgid ""
"The function is called with a single argument *obj* that identifies the "
"context in which the unraisable exception occurred. If possible, the repr of"
" *obj* will be printed in the warning message."
msgstr ""

#: ../../c-api/exceptions.rst:87
msgid "An exception must be set when calling this function."
msgstr ""

#: ../../c-api/exceptions.rst:91
msgid "Raising exceptions"
msgstr ""

#: ../../c-api/exceptions.rst:93
msgid ""
"These functions help you set the current thread's error indicator. For "
"convenience, some of these functions will always return a ``NULL`` pointer "
"for use in a ``return`` statement."
msgstr ""

#: ../../c-api/exceptions.rst:100
msgid ""
"This is the most common way to set the error indicator.  The first argument "
"specifies the exception type; it is normally one of the standard exceptions,"
" e.g. :c:data:`PyExc_RuntimeError`.  You need not create a new :term:`strong"
" reference` to it (e.g. with :c:func:`Py_INCREF`). The second argument is an"
" error message; it is decoded from ``'utf-8'``."
msgstr ""

#: ../../c-api/exceptions.rst:109
msgid ""
"This function is similar to :c:func:`PyErr_SetString` but lets you specify "
"an arbitrary Python object for the \"value\" of the exception."
msgstr ""

#: ../../c-api/exceptions.rst:115
msgid ""
"This function sets the error indicator and returns ``NULL``.  *exception* "
"should be a Python exception class.  The *format* and subsequent parameters "
"help format the error message; they have the same meaning and values as in "
":c:func:`PyUnicode_FromFormat`. *format* is an ASCII-encoded string."
msgstr ""

#: ../../c-api/exceptions.rst:124
msgid ""
"Same as :c:func:`PyErr_Format`, but taking a :c:type:`va_list` argument "
"rather than a variable number of arguments."
msgstr ""

#: ../../c-api/exceptions.rst:132
msgid "This is a shorthand for ``PyErr_SetObject(type, Py_None)``."
msgstr ""

#: ../../c-api/exceptions.rst:137
msgid ""
"This is a shorthand for ``PyErr_SetString(PyExc_TypeError, message)``, where"
" *message* indicates that a built-in operation was invoked with an illegal "
"argument.  It is mostly for internal use."
msgstr ""

#: ../../c-api/exceptions.rst:144
msgid ""
"This is a shorthand for ``PyErr_SetNone(PyExc_MemoryError)``; it returns "
"``NULL`` so an object allocation function can write ``return "
"PyErr_NoMemory();`` when it runs out of memory."
msgstr ""

#: ../../c-api/exceptions.rst:153
msgid ""
"This is a convenience function to raise an exception when a C library "
"function has returned an error and set the C variable :c:data:`errno`.  It "
"constructs a tuple object whose first item is the integer :c:data:`errno` "
"value and whose second item is the corresponding error message (gotten from "
":c:func:`!strerror`), and then calls ``PyErr_SetObject(type, object)``.  On "
"Unix, when the :c:data:`errno` value is :c:macro:`!EINTR`, indicating an "
"interrupted system call, this calls :c:func:`PyErr_CheckSignals`, and if "
"that set the error indicator, leaves it set to that.  The function always "
"returns ``NULL``, so a wrapper function around a system call can write "
"``return PyErr_SetFromErrno(type);`` when the system call returns an error."
msgstr ""

#: ../../c-api/exceptions.rst:167
msgid ""
"Similar to :c:func:`PyErr_SetFromErrno`, with the additional behavior that "
"if *filenameObject* is not ``NULL``, it is passed to the constructor of "
"*type* as a third parameter.  In the case of :exc:`OSError` exception, this "
"is used to define the :attr:`!filename` attribute of the exception instance."
msgstr ""

#: ../../c-api/exceptions.rst:176
msgid ""
"Similar to :c:func:`PyErr_SetFromErrnoWithFilenameObject`, but takes a "
"second filename object, for raising errors when a function that takes two "
"filenames fails."
msgstr ""

#: ../../c-api/exceptions.rst:185
msgid ""
"Similar to :c:func:`PyErr_SetFromErrnoWithFilenameObject`, but the filename "
"is given as a C string.  *filename* is decoded from the :term:`filesystem "
"encoding and error handler`."
msgstr ""

#: ../../c-api/exceptions.rst:192
msgid ""
"This is a convenience function to raise :exc:`WindowsError`. If called with "
"*ierr* of ``0``, the error code returned by a call to "
":c:func:`!GetLastError` is used instead.  It calls the Win32 function "
":c:func:`!FormatMessage` to retrieve the Windows description of error code "
"given by *ierr* or :c:func:`!GetLastError`, then it constructs a tuple "
"object whose first item is the *ierr* value and whose second item is the "
"corresponding error message (gotten from :c:func:`!FormatMessage`), and then"
" calls ``PyErr_SetObject(PyExc_WindowsError, object)``. This function always"
" returns ``NULL``."
msgstr ""

#: ../../c-api/exceptions.rst:201 ../../c-api/exceptions.rst:209
#: ../../c-api/exceptions.rst:220 ../../c-api/exceptions.rst:230
#: ../../c-api/exceptions.rst:238 ../../c-api/exceptions.rst:248
msgid ":ref:`Availability <availability>`: Windows."
msgstr ""

#: ../../c-api/exceptions.rst:206
msgid ""
"Similar to :c:func:`PyErr_SetFromWindowsErr`, with an additional parameter "
"specifying the exception type to be raised."
msgstr ""

#: ../../c-api/exceptions.rst:214
msgid ""
"Similar to :c:func:`PyErr_SetFromWindowsErr`, with the additional behavior "
"that if *filename* is not ``NULL``, it is decoded from the filesystem "
"encoding (:func:`os.fsdecode`) and passed to the constructor of "
":exc:`OSError` as a third parameter to be used to define the "
":attr:`!filename` attribute of the exception instance."
msgstr ""

#: ../../c-api/exceptions.rst:225
msgid ""
"Similar to :c:func:`PyErr_SetExcFromWindowsErr`, with the additional "
"behavior that if *filename* is not ``NULL``, it is passed to the constructor"
" of :exc:`OSError` as a third parameter to be used to define the "
":attr:`!filename` attribute of the exception instance."
msgstr ""

#: ../../c-api/exceptions.rst:235
msgid ""
"Similar to :c:func:`PyErr_SetExcFromWindowsErrWithFilenameObject`, but "
"accepts a second filename object."
msgstr ""

#: ../../c-api/exceptions.rst:245
msgid ""
"Similar to :c:func:`PyErr_SetFromWindowsErrWithFilename`, with an additional"
" parameter specifying the exception type to be raised."
msgstr ""

#: ../../c-api/exceptions.rst:253
msgid ""
"This is a convenience function to raise :exc:`ImportError`. *msg* will be "
"set as the exception's message string. *name* and *path*, both of which can "
"be ``NULL``, will be set as the :exc:`ImportError`'s respective ``name`` and"
" ``path`` attributes."
msgstr ""

#: ../../c-api/exceptions.rst:263
msgid ""
"Much like :c:func:`PyErr_SetImportError` but this function allows for "
"specifying a subclass of :exc:`ImportError` to raise."
msgstr ""

#: ../../c-api/exceptions.rst:271
msgid ""
"Set file, line, and offset information for the current exception.  If the "
"current exception is not a :exc:`SyntaxError`, then it sets additional "
"attributes, which make the exception printing subsystem think the exception "
"is a :exc:`SyntaxError`."
msgstr ""

#: ../../c-api/exceptions.rst:281
msgid ""
"Like :c:func:`PyErr_SyntaxLocationObject`, but *filename* is a byte string "
"decoded from the :term:`filesystem encoding and error handler`."
msgstr ""

#: ../../c-api/exceptions.rst:289
msgid ""
"Like :c:func:`PyErr_SyntaxLocationEx`, but the *col_offset* parameter is "
"omitted."
msgstr ""

#: ../../c-api/exceptions.rst:295
msgid ""
"This is a shorthand for ``PyErr_SetString(PyExc_SystemError, message)``, "
"where *message* indicates that an internal operation (e.g. a Python/C API "
"function) was invoked with an illegal argument.  It is mostly for internal "
"use."
msgstr ""

#: ../../c-api/exceptions.rst:302
msgid "Issuing warnings"
msgstr ""

#: ../../c-api/exceptions.rst:304
msgid ""
"Use these functions to issue warnings from C code.  They mirror similar "
"functions exported by the Python :mod:`warnings` module.  They normally "
"print a warning message to *sys.stderr*; however, it is also possible that "
"the user has specified that warnings are to be turned into errors, and in "
"that case they will raise an exception.  It is also possible that the "
"functions raise an exception because of a problem with the warning "
"machinery. The return value is ``0`` if no exception is raised, or ``-1`` if"
" an exception is raised.  (It is not possible to determine whether a warning"
" message is actually printed, nor what the reason is for the exception; this"
" is intentional.)  If an exception is raised, the caller should do its "
"normal exception handling (for example, :c:func:`Py_DECREF` owned references"
" and return an error value)."
msgstr ""

#: ../../c-api/exceptions.rst:319
msgid ""
"Issue a warning message.  The *category* argument is a warning category (see"
" below) or ``NULL``; the *message* argument is a UTF-8 encoded string.  "
"*stack_level* is a positive number giving a number of stack frames; the "
"warning will be issued from the  currently executing line of code in that "
"stack frame.  A *stack_level* of 1 is the function calling "
":c:func:`PyErr_WarnEx`, 2 is  the function above that, and so forth."
msgstr ""

#: ../../c-api/exceptions.rst:326
msgid ""
"Warning categories must be subclasses of :c:data:`PyExc_Warning`; "
":c:data:`PyExc_Warning` is a subclass of :c:data:`PyExc_Exception`; the "
"default warning category is :c:data:`PyExc_RuntimeWarning`. The standard "
"Python warning categories are available as global variables whose names are "
"enumerated at :ref:`standardwarningcategories`."
msgstr ""

#: ../../c-api/exceptions.rst:332
msgid ""
"For information about warning control, see the documentation for the "
":mod:`warnings` module and the :option:`-W` option in the command line "
"documentation.  There is no C API for warning control."
msgstr ""

#: ../../c-api/exceptions.rst:339
msgid ""
"Issue a warning message with explicit control over all warning attributes.  "
"This is a straightforward wrapper around the Python function "
":func:`warnings.warn_explicit`; see there for more information.  The "
"*module* and *registry* arguments may be set to ``NULL`` to get the default "
"effect described there."
msgstr ""

#: ../../c-api/exceptions.rst:350
msgid ""
"Similar to :c:func:`PyErr_WarnExplicitObject` except that *message* and "
"*module* are UTF-8 encoded strings, and *filename* is decoded from the "
":term:`filesystem encoding and error handler`."
msgstr ""

#: ../../c-api/exceptions.rst:357
msgid ""
"Function similar to :c:func:`PyErr_WarnEx`, but use "
":c:func:`PyUnicode_FromFormat` to format the warning message.  *format* is "
"an ASCII-encoded string."
msgstr ""

#: ../../c-api/exceptions.rst:366
msgid ""
"Function similar to :c:func:`PyErr_WarnFormat`, but *category* is "
":exc:`ResourceWarning` and it passes *source* to "
":class:`!warnings.WarningMessage`."
msgstr ""

#: ../../c-api/exceptions.rst:373
msgid "Querying the error indicator"
msgstr ""

#: ../../c-api/exceptions.rst:377
msgid ""
"Test whether the error indicator is set.  If set, return the exception "
"*type* (the first argument to the last call to one of the ``PyErr_Set*`` "
"functions or to :c:func:`PyErr_Restore`).  If not set, return ``NULL``.  You"
" do not own a reference to the return value, so you do not need to "
":c:func:`Py_DECREF` it."
msgstr ""

#: ../../c-api/exceptions.rst:383
msgid "The caller must hold the GIL."
msgstr ""

#: ../../c-api/exceptions.rst:387
msgid ""
"Do not compare the return value to a specific exception; use "
":c:func:`PyErr_ExceptionMatches` instead, shown below.  (The comparison "
"could easily fail since the exception may be an instance instead of a class,"
" in the case of a class exception, or it may be a subclass of the expected "
"exception.)"
msgstr ""

#: ../../c-api/exceptions.rst:395
msgid ""
"Equivalent to ``PyErr_GivenExceptionMatches(PyErr_Occurred(), exc)``.  This "
"should only be called when an exception is actually set; a memory access "
"violation will occur if no exception has been raised."
msgstr ""

#: ../../c-api/exceptions.rst:402
msgid ""
"Return true if the *given* exception matches the exception type in *exc*.  "
"If *exc* is a class object, this also returns true when *given* is an "
"instance of a subclass.  If *exc* is a tuple, all exception types in the "
"tuple (and recursively in subtuples) are searched for a match."
msgstr ""

#: ../../c-api/exceptions.rst:410
msgid ""
"Retrieve the error indicator into three variables whose addresses are "
"passed. If the error indicator is not set, set all three variables to "
"``NULL``.  If it is set, it will be cleared and you own a reference to each "
"object retrieved.  The value and traceback object may be ``NULL`` even when "
"the type object is not."
msgstr ""

#: ../../c-api/exceptions.rst:417
msgid ""
"This function is normally only used by code that needs to catch exceptions "
"or by code that needs to save and restore the error indicator temporarily, "
"e.g.::"
msgstr ""

#: ../../c-api/exceptions.rst:432
msgid ""
"Set  the error indicator from the three objects.  If the error indicator is "
"already set, it is cleared first.  If the objects are ``NULL``, the error "
"indicator is cleared.  Do not pass a ``NULL`` type and non-``NULL`` value or"
" traceback.  The exception type should be a class.  Do not pass an invalid "
"exception type or value. (Violating these rules will cause subtle problems "
"later.)  This call takes away a reference to each object: you must own a "
"reference to each object before the call and after the call you no longer "
"own these references.  (If you don't understand this, don't use this "
"function.  I warned you.)"
msgstr ""

#: ../../c-api/exceptions.rst:444
msgid ""
"This function is normally only used by code that needs to save and restore "
"the error indicator temporarily.  Use :c:func:`PyErr_Fetch` to save the "
"current error indicator."
msgstr ""

#: ../../c-api/exceptions.rst:451
msgid ""
"Under certain circumstances, the values returned by :c:func:`PyErr_Fetch` "
"below can be \"unnormalized\", meaning that ``*exc`` is a class object but "
"``*val`` is not an instance of the  same class.  This function can be used "
"to instantiate the class in that case.  If the values are already "
"normalized, nothing happens. The delayed normalization is implemented to "
"improve performance."
msgstr ""

#: ../../c-api/exceptions.rst:459
msgid ""
"This function *does not* implicitly set the "
":attr:`~BaseException.__traceback__` attribute on the exception value. If "
"setting the traceback appropriately is desired, the following additional "
"snippet is needed::"
msgstr ""

#: ../../c-api/exceptions.rst:471
msgid ""
"Retrieve the active exception instance, as would be returned by "
":func:`sys.exception`. This refers to an exception that was *already "
"caught*, not to an exception that was freshly raised. Returns a new "
"reference to the exception or ``NULL``. Does not modify the interpreter's "
"exception state."
msgstr ""

#: ../../c-api/exceptions.rst:478
msgid ""
"This function is not normally used by code that wants to handle exceptions. "
"Rather, it can be used when code needs to save and restore the exception "
"state temporarily.  Use :c:func:`PyErr_SetHandledException` to restore or "
"clear the exception state."
msgstr ""

#: ../../c-api/exceptions.rst:487
msgid ""
"Set the active exception, as known from ``sys.exception()``.  This refers to"
" an exception that was *already caught*, not to an exception that was "
"freshly raised. To clear the exception state, pass ``NULL``."
msgstr ""

#: ../../c-api/exceptions.rst:494
msgid ""
"This function is not normally used by code that wants to handle exceptions. "
"Rather, it can be used when code needs to save and restore the exception "
"state temporarily.  Use :c:func:`PyErr_GetHandledException` to get the "
"exception state."
msgstr ""

#: ../../c-api/exceptions.rst:503
msgid ""
"Retrieve the old-style representation of the exception info, as known from "
":func:`sys.exc_info`.  This refers to an exception that was *already "
"caught*, not to an exception that was freshly raised.  Returns new "
"references for the three objects, any of which may be ``NULL``.  Does not "
"modify the exception info state.  This function is kept for backwards "
"compatibility. Prefer using :c:func:`PyErr_GetHandledException`."
msgstr ""

#: ../../c-api/exceptions.rst:512
msgid ""
"This function is not normally used by code that wants to handle exceptions. "
"Rather, it can be used when code needs to save and restore the exception "
"state temporarily.  Use :c:func:`PyErr_SetExcInfo` to restore or clear the "
"exception state."
msgstr ""

#: ../../c-api/exceptions.rst:522
msgid ""
"Set the exception info, as known from ``sys.exc_info()``.  This refers to an"
" exception that was *already caught*, not to an exception that was freshly "
"raised.  This function steals the references of the arguments. To clear the "
"exception state, pass ``NULL`` for all three arguments. This function is "
"kept for backwards compatibility. Prefer using "
":c:func:`PyErr_SetHandledException`."
msgstr ""

#: ../../c-api/exceptions.rst:531
msgid ""
"This function is not normally used by code that wants to handle exceptions. "
"Rather, it can be used when code needs to save and restore the exception "
"state temporarily.  Use :c:func:`PyErr_GetExcInfo` to read the exception "
"state."
msgstr ""

#: ../../c-api/exceptions.rst:538
msgid ""
"The ``type`` and ``traceback`` arguments are no longer used and can be NULL."
" The interpreter now derives them from the exception instance (the ``value``"
" argument). The function still steals references of all three arguments."
msgstr ""

#: ../../c-api/exceptions.rst:546
msgid "Signal Handling"
msgstr ""

#: ../../c-api/exceptions.rst:556
msgid "This function interacts with Python's signal handling."
msgstr ""

#: ../../c-api/exceptions.rst:558
msgid ""
"If the function is called from the main thread and under the main Python "
"interpreter, it checks whether a signal has been sent to the processes and "
"if so, invokes the corresponding signal handler.  If the :mod:`signal` "
"module is supported, this can invoke a signal handler written in Python."
msgstr ""

#: ../../c-api/exceptions.rst:563
msgid ""
"The function attempts to handle all pending signals, and then returns ``0``."
" However, if a Python signal handler raises an exception, the error "
"indicator is set and the function returns ``-1`` immediately (such that "
"other pending signals may not have been handled yet: they will be on the "
"next :c:func:`PyErr_CheckSignals()` invocation)."
msgstr ""

#: ../../c-api/exceptions.rst:569
msgid ""
"If the function is called from a non-main thread, or under a non-main Python"
" interpreter, it does nothing and returns ``0``."
msgstr ""

#: ../../c-api/exceptions.rst:572
msgid ""
"This function can be called by long-running C code that wants to be "
"interruptible by user requests (such as by pressing Ctrl-C)."
msgstr ""

#: ../../c-api/exceptions.rst:576
msgid ""
"The default Python signal handler for :c:macro:`!SIGINT` raises the "
":exc:`KeyboardInterrupt` exception."
msgstr ""

#: ../../c-api/exceptions.rst:587
msgid ""
"Simulate the effect of a :c:macro:`!SIGINT` signal arriving. This is "
"equivalent to ``PyErr_SetInterruptEx(SIGINT)``."
msgstr ""

#: ../../c-api/exceptions.rst:591 ../../c-api/exceptions.rst:618
msgid ""
"This function is async-signal-safe.  It can be called without the "
":term:`GIL` and from a C signal handler."
msgstr ""

#: ../../c-api/exceptions.rst:601
msgid ""
"Simulate the effect of a signal arriving. The next time "
":c:func:`PyErr_CheckSignals` is called,  the Python signal handler for the "
"given signal number will be called."
msgstr ""

#: ../../c-api/exceptions.rst:605
msgid ""
"This function can be called by C code that sets up its own signal handling "
"and wants Python signal handlers to be invoked as expected when an "
"interruption is requested (for example when the user presses Ctrl-C to "
"interrupt an operation)."
msgstr ""

#: ../../c-api/exceptions.rst:610
msgid ""
"If the given signal isn't handled by Python (it was set to "
":py:const:`signal.SIG_DFL` or :py:const:`signal.SIG_IGN`), it will be "
"ignored."
msgstr ""

#: ../../c-api/exceptions.rst:613
msgid ""
"If *signum* is outside of the allowed range of signal numbers, ``-1`` is "
"returned.  Otherwise, ``0`` is returned.  The error indicator is never "
"changed by this function."
msgstr ""

#: ../../c-api/exceptions.rst:626
msgid ""
"This utility function specifies a file descriptor to which the signal number"
" is written as a single byte whenever a signal is received. *fd* must be "
"non-blocking. It returns the previous such file descriptor."
msgstr ""

#: ../../c-api/exceptions.rst:630
msgid ""
"The value ``-1`` disables the feature; this is the initial state. This is "
"equivalent to :func:`signal.set_wakeup_fd` in Python, but without any error "
"checking.  *fd* should be a valid file descriptor.  The function should only"
" be called from the main thread."
msgstr ""

#: ../../c-api/exceptions.rst:635
msgid "On Windows, the function now also supports socket handles."
msgstr ""

#: ../../c-api/exceptions.rst:640
msgid "Exception Classes"
msgstr ""

#: ../../c-api/exceptions.rst:644
msgid ""
"This utility function creates and returns a new exception class. The *name* "
"argument must be the name of the new exception, a C string of the form "
"``module.classname``.  The *base* and *dict* arguments are normally "
"``NULL``. This creates a class object derived from :exc:`Exception` "
"(accessible in C as :c:data:`PyExc_Exception`)."
msgstr ""

#: ../../c-api/exceptions.rst:650
msgid ""
"The :attr:`!__module__` attribute of the new class is set to the first part "
"(up to the last dot) of the *name* argument, and the class name is set to "
"the last part (after the last dot).  The *base* argument can be used to "
"specify alternate base classes; it can either be only one class or a tuple "
"of classes. The *dict* argument can be used to specify a dictionary of class"
" variables and methods."
msgstr ""

#: ../../c-api/exceptions.rst:659
msgid ""
"Same as :c:func:`PyErr_NewException`, except that the new exception class "
"can easily be given a docstring: If *doc* is non-``NULL``, it will be used "
"as the docstring for the exception class."
msgstr ""

#: ../../c-api/exceptions.rst:667
msgid "Exception Objects"
msgstr ""

#: ../../c-api/exceptions.rst:671
msgid ""
"Return the traceback associated with the exception as a new reference, as "
"accessible from Python through the :attr:`~BaseException.__traceback__` "
"attribute. If there is no traceback associated, this returns ``NULL``."
msgstr ""

#: ../../c-api/exceptions.rst:679
msgid ""
"Set the traceback associated with the exception to *tb*.  Use ``Py_None`` to"
" clear it."
msgstr ""

#: ../../c-api/exceptions.rst:685
msgid ""
"Return the context (another exception instance during whose handling *ex* "
"was raised) associated with the exception as a new reference, as accessible "
"from Python through the :attr:`~BaseException.__context__` attribute. If "
"there is no context associated, this returns ``NULL``."
msgstr ""

#: ../../c-api/exceptions.rst:693
msgid ""
"Set the context associated with the exception to *ctx*.  Use ``NULL`` to "
"clear it.  There is no type check to make sure that *ctx* is an exception "
"instance. This steals a reference to *ctx*."
msgstr ""

#: ../../c-api/exceptions.rst:700
msgid ""
"Return the cause (either an exception instance, or ``None``, set by ``raise "
"... from ...``) associated with the exception as a new reference, as "
"accessible from Python through the :attr:`~BaseException.__cause__` "
"attribute."
msgstr ""

#: ../../c-api/exceptions.rst:708
msgid ""
"Set the cause associated with the exception to *cause*.  Use ``NULL`` to "
"clear it.  There is no type check to make sure that *cause* is either an "
"exception instance or ``None``.  This steals a reference to *cause*."
msgstr ""

#: ../../c-api/exceptions.rst:712
msgid ""
"The :attr:`~BaseException.__suppress_context__` attribute is implicitly set "
"to ``True`` by this function."
msgstr ""

#: ../../c-api/exceptions.rst:719
msgid "Unicode Exception Objects"
msgstr ""

#: ../../c-api/exceptions.rst:721
msgid ""
"The following functions are used to create and modify Unicode exceptions "
"from C."
msgstr ""

#: ../../c-api/exceptions.rst:725
msgid ""
"Create a :class:`UnicodeDecodeError` object with the attributes *encoding*, "
"*object*, *length*, *start*, *end* and *reason*. *encoding* and *reason* are"
" UTF-8 encoded strings."
msgstr ""

#: ../../c-api/exceptions.rst:732
msgid "Return the *encoding* attribute of the given exception object."
msgstr ""

#: ../../c-api/exceptions.rst:738
msgid "Return the *object* attribute of the given exception object."
msgstr ""

#: ../../c-api/exceptions.rst:744
msgid ""
"Get the *start* attribute of the given exception object and place it into "
"*\\*start*.  *start* must not be ``NULL``.  Return ``0`` on success, ``-1`` "
"on failure."
msgstr ""

#: ../../c-api/exceptions.rst:752
msgid ""
"Set the *start* attribute of the given exception object to *start*.  Return "
"``0`` on success, ``-1`` on failure."
msgstr ""

#: ../../c-api/exceptions.rst:759
msgid ""
"Get the *end* attribute of the given exception object and place it into "
"*\\*end*.  *end* must not be ``NULL``.  Return ``0`` on success, ``-1`` on "
"failure."
msgstr ""

#: ../../c-api/exceptions.rst:767
msgid ""
"Set the *end* attribute of the given exception object to *end*.  Return "
"``0`` on success, ``-1`` on failure."
msgstr ""

#: ../../c-api/exceptions.rst:774
msgid "Return the *reason* attribute of the given exception object."
msgstr ""

#: ../../c-api/exceptions.rst:780
msgid ""
"Set the *reason* attribute of the given exception object to *reason*.  "
"Return ``0`` on success, ``-1`` on failure."
msgstr ""

#: ../../c-api/exceptions.rst:787
msgid "Recursion Control"
msgstr ""

#: ../../c-api/exceptions.rst:789
msgid ""
"These two functions provide a way to perform safe recursive calls at the C "
"level, both in the core and in extension modules.  They are needed if the "
"recursive code does not necessarily invoke Python code (which tracks its "
"recursion depth automatically). They are also not needed for *tp_call* "
"implementations because the :ref:`call protocol <call>` takes care of "
"recursion handling."
msgstr ""

#: ../../c-api/exceptions.rst:798
msgid "Marks a point where a recursive C-level call is about to be performed."
msgstr ""

#: ../../c-api/exceptions.rst:800
msgid ""
"If :c:macro:`!USE_STACKCHECK` is defined, this function checks if the OS "
"stack overflowed using :c:func:`PyOS_CheckStack`.  If this is the case, it "
"sets a :exc:`MemoryError` and returns a nonzero value."
msgstr ""

#: ../../c-api/exceptions.rst:804
msgid ""
"The function then checks if the recursion limit is reached.  If this is the "
"case, a :exc:`RecursionError` is set and a nonzero value is returned. "
"Otherwise, zero is returned."
msgstr ""

#: ../../c-api/exceptions.rst:808
msgid ""
"*where* should be a UTF-8 encoded string such as ``\" in instance check\"`` "
"to be concatenated to the :exc:`RecursionError` message caused by the "
"recursion depth limit."
msgstr ""

#: ../../c-api/exceptions.rst:812 ../../c-api/exceptions.rst:820
msgid ""
"This function is now also available in the :ref:`limited API <limited-c-"
"api>`."
msgstr ""

#: ../../c-api/exceptions.rst:817
msgid ""
"Ends a :c:func:`Py_EnterRecursiveCall`.  Must be called once for each "
"*successful* invocation of :c:func:`Py_EnterRecursiveCall`."
msgstr ""

#: ../../c-api/exceptions.rst:823
msgid ""
"Properly implementing :c:member:`~PyTypeObject.tp_repr` for container types "
"requires special recursion handling.  In addition to protecting the stack, "
":c:member:`~PyTypeObject.tp_repr` also needs to track objects to prevent "
"cycles.  The following two functions facilitate this functionality.  "
"Effectively, these are the C equivalent to :func:`reprlib.recursive_repr`."
msgstr ""

#: ../../c-api/exceptions.rst:831
msgid ""
"Called at the beginning of the :c:member:`~PyTypeObject.tp_repr` "
"implementation to detect cycles."
msgstr ""

#: ../../c-api/exceptions.rst:834
msgid ""
"If the object has already been processed, the function returns a positive "
"integer.  In that case the :c:member:`~PyTypeObject.tp_repr` implementation "
"should return a string object indicating a cycle.  As examples, "
":class:`dict` objects return ``{...}`` and :class:`list` objects return "
"``[...]``."
msgstr ""

#: ../../c-api/exceptions.rst:840
msgid ""
"The function will return a negative integer if the recursion limit is "
"reached.  In that case the :c:member:`~PyTypeObject.tp_repr` implementation "
"should typically return ``NULL``."
msgstr ""

#: ../../c-api/exceptions.rst:844
msgid ""
"Otherwise, the function returns zero and the "
":c:member:`~PyTypeObject.tp_repr` implementation can continue normally."
msgstr ""

#: ../../c-api/exceptions.rst:849
msgid ""
"Ends a :c:func:`Py_ReprEnter`.  Must be called once for each invocation of "
":c:func:`Py_ReprEnter` that returns zero."
msgstr ""

#: ../../c-api/exceptions.rst:856
msgid "Standard Exceptions"
msgstr ""

#: ../../c-api/exceptions.rst:858
msgid ""
"All standard Python exceptions are available as global variables whose names"
" are ``PyExc_`` followed by the Python exception name.  These have the type "
":c:expr:`PyObject*`; they are all class objects.  For completeness, here are"
" all the variables:"
msgstr ""

#: ../../c-api/exceptions.rst:919 ../../c-api/exceptions.rst:1052
#: ../../c-api/exceptions.rst:1097
msgid "C Name"
msgstr ""

#: ../../c-api/exceptions.rst:919 ../../c-api/exceptions.rst:1097
msgid "Python Name"
msgstr ""

#: ../../c-api/exceptions.rst:919 ../../c-api/exceptions.rst:1052
#: ../../c-api/exceptions.rst:1097
msgid "Notes"
msgstr ""

#: ../../c-api/exceptions.rst:921
msgid ":c:data:`PyExc_BaseException`"
msgstr ""

#: ../../c-api/exceptions.rst:921
msgid ":exc:`BaseException`"
msgstr ""

#: ../../c-api/exceptions.rst:921 ../../c-api/exceptions.rst:923
#: ../../c-api/exceptions.rst:925 ../../c-api/exceptions.rst:971
#: ../../c-api/exceptions.rst:983
msgid "[1]_"
msgstr ""

#: ../../c-api/exceptions.rst:923
msgid ":c:data:`PyExc_Exception`"
msgstr ""

#: ../../c-api/exceptions.rst:923
msgid ":exc:`Exception`"
msgstr ""

#: ../../c-api/exceptions.rst:925
msgid ":c:data:`PyExc_ArithmeticError`"
msgstr ""

#: ../../c-api/exceptions.rst:925
msgid ":exc:`ArithmeticError`"
msgstr ""

#: ../../c-api/exceptions.rst:927
msgid ":c:data:`PyExc_AssertionError`"
msgstr ""

#: ../../c-api/exceptions.rst:927
msgid ":exc:`AssertionError`"
msgstr ""

#: ../../c-api/exceptions.rst:929
msgid ":c:data:`PyExc_AttributeError`"
msgstr ""

#: ../../c-api/exceptions.rst:929
msgid ":exc:`AttributeError`"
msgstr ""

#: ../../c-api/exceptions.rst:931
msgid ":c:data:`PyExc_BlockingIOError`"
msgstr ""

#: ../../c-api/exceptions.rst:931
msgid ":exc:`BlockingIOError`"
msgstr ""

#: ../../c-api/exceptions.rst:933
msgid ":c:data:`PyExc_BrokenPipeError`"
msgstr ""

#: ../../c-api/exceptions.rst:933
msgid ":exc:`BrokenPipeError`"
msgstr ""

#: ../../c-api/exceptions.rst:935
msgid ":c:data:`PyExc_BufferError`"
msgstr ""

#: ../../c-api/exceptions.rst:935
msgid ":exc:`BufferError`"
msgstr ""

#: ../../c-api/exceptions.rst:937
msgid ":c:data:`PyExc_ChildProcessError`"
msgstr ""

#: ../../c-api/exceptions.rst:937
msgid ":exc:`ChildProcessError`"
msgstr ""

#: ../../c-api/exceptions.rst:939
msgid ":c:data:`PyExc_ConnectionAbortedError`"
msgstr ""

#: ../../c-api/exceptions.rst:939
msgid ":exc:`ConnectionAbortedError`"
msgstr ""

#: ../../c-api/exceptions.rst:941
msgid ":c:data:`PyExc_ConnectionError`"
msgstr ""

#: ../../c-api/exceptions.rst:941
msgid ":exc:`ConnectionError`"
msgstr ""

#: ../../c-api/exceptions.rst:943
msgid ":c:data:`PyExc_ConnectionRefusedError`"
msgstr ""

#: ../../c-api/exceptions.rst:943
msgid ":exc:`ConnectionRefusedError`"
msgstr ""

#: ../../c-api/exceptions.rst:945
msgid ":c:data:`PyExc_ConnectionResetError`"
msgstr ""

#: ../../c-api/exceptions.rst:945
msgid ":exc:`ConnectionResetError`"
msgstr ""

#: ../../c-api/exceptions.rst:947
msgid ":c:data:`PyExc_EOFError`"
msgstr ""

#: ../../c-api/exceptions.rst:947
msgid ":exc:`EOFError`"
msgstr ""

#: ../../c-api/exceptions.rst:949
msgid ":c:data:`PyExc_FileExistsError`"
msgstr ""

#: ../../c-api/exceptions.rst:949
msgid ":exc:`FileExistsError`"
msgstr ""

#: ../../c-api/exceptions.rst:951
msgid ":c:data:`PyExc_FileNotFoundError`"
msgstr ""

#: ../../c-api/exceptions.rst:951
msgid ":exc:`FileNotFoundError`"
msgstr ""

#: ../../c-api/exceptions.rst:953
msgid ":c:data:`PyExc_FloatingPointError`"
msgstr ""

#: ../../c-api/exceptions.rst:953
msgid ":exc:`FloatingPointError`"
msgstr ""

#: ../../c-api/exceptions.rst:955
msgid ":c:data:`PyExc_GeneratorExit`"
msgstr ""

#: ../../c-api/exceptions.rst:955
msgid ":exc:`GeneratorExit`"
msgstr ""

#: ../../c-api/exceptions.rst:957
msgid ":c:data:`PyExc_ImportError`"
msgstr ""

#: ../../c-api/exceptions.rst:957
msgid ":exc:`ImportError`"
msgstr ""

#: ../../c-api/exceptions.rst:959
msgid ":c:data:`PyExc_IndentationError`"
msgstr ""

#: ../../c-api/exceptions.rst:959
msgid ":exc:`IndentationError`"
msgstr ""

#: ../../c-api/exceptions.rst:961
msgid ":c:data:`PyExc_IndexError`"
msgstr ""

#: ../../c-api/exceptions.rst:961
msgid ":exc:`IndexError`"
msgstr ""

#: ../../c-api/exceptions.rst:963
msgid ":c:data:`PyExc_InterruptedError`"
msgstr ""

#: ../../c-api/exceptions.rst:963
msgid ":exc:`InterruptedError`"
msgstr ""

#: ../../c-api/exceptions.rst:965
msgid ":c:data:`PyExc_IsADirectoryError`"
msgstr ""

#: ../../c-api/exceptions.rst:965
msgid ":exc:`IsADirectoryError`"
msgstr ""

#: ../../c-api/exceptions.rst:967
msgid ":c:data:`PyExc_KeyError`"
msgstr ""

#: ../../c-api/exceptions.rst:967
msgid ":exc:`KeyError`"
msgstr ""

#: ../../c-api/exceptions.rst:969
msgid ":c:data:`PyExc_KeyboardInterrupt`"
msgstr ""

#: ../../c-api/exceptions.rst:969
msgid ":exc:`KeyboardInterrupt`"
msgstr ""

#: ../../c-api/exceptions.rst:971
msgid ":c:data:`PyExc_LookupError`"
msgstr ""

#: ../../c-api/exceptions.rst:971
msgid ":exc:`LookupError`"
msgstr ""

#: ../../c-api/exceptions.rst:973
msgid ":c:data:`PyExc_MemoryError`"
msgstr ""

#: ../../c-api/exceptions.rst:973
msgid ":exc:`MemoryError`"
msgstr ""

#: ../../c-api/exceptions.rst:975
msgid ":c:data:`PyExc_ModuleNotFoundError`"
msgstr ""

#: ../../c-api/exceptions.rst:975
msgid ":exc:`ModuleNotFoundError`"
msgstr ""

#: ../../c-api/exceptions.rst:977
msgid ":c:data:`PyExc_NameError`"
msgstr ""

#: ../../c-api/exceptions.rst:977
msgid ":exc:`NameError`"
msgstr ""

#: ../../c-api/exceptions.rst:979
msgid ":c:data:`PyExc_NotADirectoryError`"
msgstr ""

#: ../../c-api/exceptions.rst:979
msgid ":exc:`NotADirectoryError`"
msgstr ""

#: ../../c-api/exceptions.rst:981
msgid ":c:data:`PyExc_NotImplementedError`"
msgstr ""

#: ../../c-api/exceptions.rst:981
msgid ":exc:`NotImplementedError`"
msgstr ""

#: ../../c-api/exceptions.rst:983
msgid ":c:data:`PyExc_OSError`"
msgstr ""

#: ../../c-api/exceptions.rst:983
msgid ":exc:`OSError`"
msgstr ""

#: ../../c-api/exceptions.rst:985
msgid ":c:data:`PyExc_OverflowError`"
msgstr ""

#: ../../c-api/exceptions.rst:985
msgid ":exc:`OverflowError`"
msgstr ""

#: ../../c-api/exceptions.rst:987
msgid ":c:data:`PyExc_PermissionError`"
msgstr ""

#: ../../c-api/exceptions.rst:987
msgid ":exc:`PermissionError`"
msgstr ""

#: ../../c-api/exceptions.rst:989
msgid ":c:data:`PyExc_ProcessLookupError`"
msgstr ""

#: ../../c-api/exceptions.rst:989
msgid ":exc:`ProcessLookupError`"
msgstr ""

#: ../../c-api/exceptions.rst:991
msgid ":c:data:`PyExc_RecursionError`"
msgstr ""

#: ../../c-api/exceptions.rst:991
msgid ":exc:`RecursionError`"
msgstr ""

#: ../../c-api/exceptions.rst:993
msgid ":c:data:`PyExc_ReferenceError`"
msgstr ""

#: ../../c-api/exceptions.rst:993
msgid ":exc:`ReferenceError`"
msgstr ""

#: ../../c-api/exceptions.rst:995
msgid ":c:data:`PyExc_RuntimeError`"
msgstr ""

#: ../../c-api/exceptions.rst:995
msgid ":exc:`RuntimeError`"
msgstr ""

#: ../../c-api/exceptions.rst:997
msgid ":c:data:`PyExc_StopAsyncIteration`"
msgstr ""

#: ../../c-api/exceptions.rst:997
msgid ":exc:`StopAsyncIteration`"
msgstr ""

#: ../../c-api/exceptions.rst:999
msgid ":c:data:`PyExc_StopIteration`"
msgstr ""

#: ../../c-api/exceptions.rst:999
msgid ":exc:`StopIteration`"
msgstr ""

#: ../../c-api/exceptions.rst:1001
msgid ":c:data:`PyExc_SyntaxError`"
msgstr ""

#: ../../c-api/exceptions.rst:1001
msgid ":exc:`SyntaxError`"
msgstr ""

#: ../../c-api/exceptions.rst:1003
msgid ":c:data:`PyExc_SystemError`"
msgstr ""

#: ../../c-api/exceptions.rst:1003
msgid ":exc:`SystemError`"
msgstr ""

#: ../../c-api/exceptions.rst:1005
msgid ":c:data:`PyExc_SystemExit`"
msgstr ""

#: ../../c-api/exceptions.rst:1005
msgid ":exc:`SystemExit`"
msgstr ""

#: ../../c-api/exceptions.rst:1007
msgid ":c:data:`PyExc_TabError`"
msgstr ""

#: ../../c-api/exceptions.rst:1007
msgid ":exc:`TabError`"
msgstr ""

#: ../../c-api/exceptions.rst:1009
msgid ":c:data:`PyExc_TimeoutError`"
msgstr ""

#: ../../c-api/exceptions.rst:1009
msgid ":exc:`TimeoutError`"
msgstr ""

#: ../../c-api/exceptions.rst:1011
msgid ":c:data:`PyExc_TypeError`"
msgstr ""

#: ../../c-api/exceptions.rst:1011
msgid ":exc:`TypeError`"
msgstr ""

#: ../../c-api/exceptions.rst:1013
msgid ":c:data:`PyExc_UnboundLocalError`"
msgstr ""

#: ../../c-api/exceptions.rst:1013
msgid ":exc:`UnboundLocalError`"
msgstr ""

#: ../../c-api/exceptions.rst:1015
msgid ":c:data:`PyExc_UnicodeDecodeError`"
msgstr ""

#: ../../c-api/exceptions.rst:1015
msgid ":exc:`UnicodeDecodeError`"
msgstr ""

#: ../../c-api/exceptions.rst:1017
msgid ":c:data:`PyExc_UnicodeEncodeError`"
msgstr ""

#: ../../c-api/exceptions.rst:1017
msgid ":exc:`UnicodeEncodeError`"
msgstr ""

#: ../../c-api/exceptions.rst:1019
msgid ":c:data:`PyExc_UnicodeError`"
msgstr ""

#: ../../c-api/exceptions.rst:1019
msgid ":exc:`UnicodeError`"
msgstr ""

#: ../../c-api/exceptions.rst:1021
msgid ":c:data:`PyExc_UnicodeTranslateError`"
msgstr ""

#: ../../c-api/exceptions.rst:1021
msgid ":exc:`UnicodeTranslateError`"
msgstr ""

#: ../../c-api/exceptions.rst:1023
msgid ":c:data:`PyExc_ValueError`"
msgstr ""

#: ../../c-api/exceptions.rst:1023
msgid ":exc:`ValueError`"
msgstr ""

#: ../../c-api/exceptions.rst:1025
msgid ":c:data:`PyExc_ZeroDivisionError`"
msgstr ""

#: ../../c-api/exceptions.rst:1025
msgid ":exc:`ZeroDivisionError`"
msgstr ""

#: ../../c-api/exceptions.rst:1028
msgid ""
":c:data:`PyExc_BlockingIOError`, :c:data:`PyExc_BrokenPipeError`, "
":c:data:`PyExc_ChildProcessError`, :c:data:`PyExc_ConnectionError`, "
":c:data:`PyExc_ConnectionAbortedError`, "
":c:data:`PyExc_ConnectionRefusedError`, "
":c:data:`PyExc_ConnectionResetError`, :c:data:`PyExc_FileExistsError`, "
":c:data:`PyExc_FileNotFoundError`, :c:data:`PyExc_InterruptedError`, "
":c:data:`PyExc_IsADirectoryError`, :c:data:`PyExc_NotADirectoryError`, "
":c:data:`PyExc_PermissionError`, :c:data:`PyExc_ProcessLookupError` and "
":c:data:`PyExc_TimeoutError` were introduced following :pep:`3151`."
msgstr ""

#: ../../c-api/exceptions.rst:1038
msgid ":c:data:`PyExc_StopAsyncIteration` and :c:data:`PyExc_RecursionError`."
msgstr ""

#: ../../c-api/exceptions.rst:1041
msgid ":c:data:`PyExc_ModuleNotFoundError`."
msgstr ""

#: ../../c-api/exceptions.rst:1044
msgid "These are compatibility aliases to :c:data:`PyExc_OSError`:"
msgstr ""

#: ../../c-api/exceptions.rst:1054
msgid ":c:data:`!PyExc_EnvironmentError`"
msgstr ""

#: ../../c-api/exceptions.rst:1056
msgid ":c:data:`!PyExc_IOError`"
msgstr ""

#: ../../c-api/exceptions.rst:1058
msgid ":c:data:`!PyExc_WindowsError`"
msgstr ""

#: ../../c-api/exceptions.rst:1058
msgid "[2]_"
msgstr ""

#: ../../c-api/exceptions.rst:1061
msgid "These aliases used to be separate exception types."
msgstr ""

#: ../../c-api/exceptions.rst:1064 ../../c-api/exceptions.rst:1125
msgid "Notes:"
msgstr ""

#: ../../c-api/exceptions.rst:1067
msgid "This is a base class for other standard exceptions."
msgstr ""

#: ../../c-api/exceptions.rst:1070
msgid ""
"Only defined on Windows; protect code that uses this by testing that the "
"preprocessor macro ``MS_WINDOWS`` is defined."
msgstr ""

#: ../../c-api/exceptions.rst:1076
msgid "Standard Warning Categories"
msgstr ""

#: ../../c-api/exceptions.rst:1078
msgid ""
"All standard Python warning categories are available as global variables "
"whose names are ``PyExc_`` followed by the Python exception name. These have"
" the type :c:expr:`PyObject*`; they are all class objects. For completeness,"
" here are all the variables:"
msgstr ""

#: ../../c-api/exceptions.rst:1099
msgid ":c:data:`PyExc_Warning`"
msgstr ""

#: ../../c-api/exceptions.rst:1099
msgid ":exc:`Warning`"
msgstr ""

#: ../../c-api/exceptions.rst:1099
msgid "[3]_"
msgstr ""

#: ../../c-api/exceptions.rst:1101
msgid ":c:data:`PyExc_BytesWarning`"
msgstr ""

#: ../../c-api/exceptions.rst:1101
msgid ":exc:`BytesWarning`"
msgstr ""

#: ../../c-api/exceptions.rst:1103
msgid ":c:data:`PyExc_DeprecationWarning`"
msgstr ""

#: ../../c-api/exceptions.rst:1103
msgid ":exc:`DeprecationWarning`"
msgstr ""

#: ../../c-api/exceptions.rst:1105
msgid ":c:data:`PyExc_FutureWarning`"
msgstr ""

#: ../../c-api/exceptions.rst:1105
msgid ":exc:`FutureWarning`"
msgstr ""

#: ../../c-api/exceptions.rst:1107
msgid ":c:data:`PyExc_ImportWarning`"
msgstr ""

#: ../../c-api/exceptions.rst:1107
msgid ":exc:`ImportWarning`"
msgstr ""

#: ../../c-api/exceptions.rst:1109
msgid ":c:data:`PyExc_PendingDeprecationWarning`"
msgstr ""

#: ../../c-api/exceptions.rst:1109
msgid ":exc:`PendingDeprecationWarning`"
msgstr ""

#: ../../c-api/exceptions.rst:1111
msgid ":c:data:`PyExc_ResourceWarning`"
msgstr ""

#: ../../c-api/exceptions.rst:1111
msgid ":exc:`ResourceWarning`"
msgstr ""

#: ../../c-api/exceptions.rst:1113
msgid ":c:data:`PyExc_RuntimeWarning`"
msgstr ""

#: ../../c-api/exceptions.rst:1113
msgid ":exc:`RuntimeWarning`"
msgstr ""

#: ../../c-api/exceptions.rst:1115
msgid ":c:data:`PyExc_SyntaxWarning`"
msgstr ""

#: ../../c-api/exceptions.rst:1115
msgid ":exc:`SyntaxWarning`"
msgstr ""

#: ../../c-api/exceptions.rst:1117
msgid ":c:data:`PyExc_UnicodeWarning`"
msgstr ""

#: ../../c-api/exceptions.rst:1117
msgid ":exc:`UnicodeWarning`"
msgstr ""

#: ../../c-api/exceptions.rst:1119
msgid ":c:data:`PyExc_UserWarning`"
msgstr ""

#: ../../c-api/exceptions.rst:1119
msgid ":exc:`UserWarning`"
msgstr ""

#: ../../c-api/exceptions.rst:1122
msgid ":c:data:`PyExc_ResourceWarning`."
msgstr ""

#: ../../c-api/exceptions.rst:1128
msgid "This is a base class for other standard warning categories."
msgstr ""

#: ../../c-api/exceptions.rst:151
msgid "strerror (C function)"
msgstr ""

#: ../../c-api/exceptions.rst:551 ../../c-api/exceptions.rst:582
#: ../../c-api/exceptions.rst:597
msgid "module"
msgstr ""

#: ../../c-api/exceptions.rst:551 ../../c-api/exceptions.rst:582
#: ../../c-api/exceptions.rst:597
msgid "signal"
msgstr ""

#: ../../c-api/exceptions.rst:551 ../../c-api/exceptions.rst:582
msgid "SIGINT (C macro)"
msgstr ""

#: ../../c-api/exceptions.rst:551 ../../c-api/exceptions.rst:582
#: ../../c-api/exceptions.rst:597
msgid "KeyboardInterrupt (built-in exception)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_BaseException (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_Exception (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_ArithmeticError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_AssertionError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_AttributeError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_BlockingIOError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_BrokenPipeError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_BufferError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_ChildProcessError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_ConnectionAbortedError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_ConnectionError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_ConnectionRefusedError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_ConnectionResetError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_EOFError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_FileExistsError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_FileNotFoundError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_FloatingPointError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_GeneratorExit (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_ImportError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_IndentationError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_IndexError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_InterruptedError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_IsADirectoryError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_KeyError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_KeyboardInterrupt (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_LookupError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_MemoryError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_ModuleNotFoundError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_NameError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_NotADirectoryError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_NotImplementedError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_OSError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_OverflowError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_PermissionError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_ProcessLookupError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_RecursionError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_ReferenceError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_RuntimeError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_StopAsyncIteration (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_StopIteration (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_SyntaxError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_SystemError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_SystemExit (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_TabError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_TimeoutError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_TypeError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_UnboundLocalError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_UnicodeDecodeError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_UnicodeEncodeError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_UnicodeError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_UnicodeTranslateError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_ValueError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:863
msgid "PyExc_ZeroDivisionError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:1046
msgid "PyExc_EnvironmentError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:1046
msgid "PyExc_IOError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:1046
msgid "PyExc_WindowsError (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:1083
msgid "PyExc_Warning (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:1083
msgid "PyExc_BytesWarning (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:1083
msgid "PyExc_DeprecationWarning (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:1083
msgid "PyExc_FutureWarning (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:1083
msgid "PyExc_ImportWarning (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:1083
msgid "PyExc_PendingDeprecationWarning (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:1083
msgid "PyExc_ResourceWarning (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:1083
msgid "PyExc_RuntimeWarning (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:1083
msgid "PyExc_SyntaxWarning (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:1083
msgid "PyExc_UnicodeWarning (C var)"
msgstr ""

#: ../../c-api/exceptions.rst:1083
msgid "PyExc_UserWarning (C var)"
msgstr ""
